package com.inductiveautomation.ignition.gateway.llm.gateway.conversation;

import com.inductiveautomation.ignition.gateway.llm.common.model.ActionResult;
import com.inductiveautomation.ignition.gateway.llm.gateway.providers.LLMToolCall;

/**
 * Handler interface for streaming conversation responses.
 * Used by the SSE endpoint to receive real-time updates during LLM processing.
 */
public interface StreamingResponseHandler {

    /**
     * Called for each token as it's generated by the LLM.
     *
     * @param token The generated token text
     */
    void onToken(String token);

    /**
     * Called when a tool call begins execution.
     *
     * @param toolCall The tool call being executed
     */
    void onToolCallStart(LLMToolCall toolCall);

    /**
     * Called when a tool call completes with a result.
     *
     * @param toolCall The completed tool call
     * @param result The action result from the tool execution
     */
    void onToolCallComplete(LLMToolCall toolCall, ActionResult result);

    /**
     * Called when the full response is complete.
     *
     * @param response The final conversation response
     */
    void onComplete(ConversationResponse response);

    /**
     * Called when an error occurs during processing.
     *
     * @param error The exception that occurred
     */
    void onError(Exception error);

    /**
     * Creates a no-op handler that ignores all events.
     * Useful for testing or when streaming is not needed.
     */
    static StreamingResponseHandler noOp() {
        return new StreamingResponseHandler() {
            @Override
            public void onToken(String token) {}

            @Override
            public void onToolCallStart(LLMToolCall toolCall) {}

            @Override
            public void onToolCallComplete(LLMToolCall toolCall, ActionResult result) {}

            @Override
            public void onComplete(ConversationResponse response) {}

            @Override
            public void onError(Exception error) {}
        };
    }
}
